export const bikes = [
    {
        manufacturer: 'specialized',
        model: 'stumpjumper',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 140,
        shockTravel: 130,
        htAngle: [65,65.5],
        link: 'https://www.specialized.com/us/en/shop/bikes/mountain-bikes/trail-bikes/stumpjumper/c/stumpjumper#/filter:productfamily:Stumpjumper',
        picLink: 'https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/MTB-2453_PDP_Prod_01?wid=1920&hei=640&$hybris-pdp-hero-exp$}'
    },
    {
        manufacturer: 'specialized',
        model: 'stumpjumper evo',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 160,
        shockTravel: 150,
        htAngle: [63,63.5,64,64.5,65,65.5],
        link: 'https://www.specialized.com/us/en/shop/bikes/mountain-bikes/trail-bikes/stumpjumper/c/stumpjumper#/filter:productfamily:Stumpjumper$2520EVO',
        picLink: 'https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/01_MTB-2363__PDP_Product-Carousel_3840x1280?wid=1920&hei=640&$hybris-pdp-hero-exp$}'
    },
    {
        manufacturer: 'specialized',
        model: 'demo',
        bikeType: 'full suspension',
        wheelSize: 'Mullet',
        forkTravel: 200,
        shockTravel: 200,
        htAngle: [62.8],
        link: 'https://www.specialized.com/us/en/shop/bikes/mountain-bikes/downhill-mountain-bikes/c/mountaindownhill',
        picLink: 'https://theloamwolf.com/wp-content/uploads/2020/09/2021-Specialized-Demo-2.jpg'
    },
    {
        manufacturer: 'specialized',
        model: 'epic evo',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 120,
        shockTravel: 110,
        htAngle: [66.5],
        link: 'https://www.specialized.com/us/en/shop/bikes/mountain-bikes/cross-country-mountain-bikes/epic/c/epic#/filter:productfamily:Epic$2520EVO',
        picLink: 'https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/MTB-2197__PDP_Product-Carousel_EVO_3840x1280_01?wid=1920&hei=640&$hybris-pdp-hero-exp$}'
    },
    {
        manufacturer: 'specialized',
        model: 'epic',
        bikeType: 'hardtail',
        wheelSize: 29,
        forkTravel: 100,
        shockTravel: 0,
        htAngle: [68.5],
        link: 'https://www.specialized.com/us/en/shop/bikes/mountain-bikes/cross-country-mountain-bikes/epic-hardtail/c/epichardtail',
        picLink: 'https://s7d5.scene7.com/is/image/Specialized/?layer=0&wid=1920&hei=640&fmt=jpg&src=is{Specialized/pdp-product-bg-dark-fb?wid=1920&hei=640}&layer=1&src=is{Specialized/MTB-1826__PDP_Product-Carousel_3840x1280_1?wid=1920&hei=640&$hybris-pdp-hero-exp$}'
    },
    {
        manufacturer: 'specialized',
        model: 'chisel',
        bikeType: 'hardtail',
        wheelSize: 29,
        forkTravel: 100,
        shockTravel: 0,
        htAngle: [68],
        link: 'https://www.specialized.com/us/en/shop/bikes/mountain-bikes/cross-country-mountain-bikes/chisel/c/chisel',
        picLink: 'https://images.immediate.co.uk/production/volatile/sites/21/2020/09/Specialized-Chisel-XC-bike-pack-shot-dcaf1ef.jpg?quality=90&resize=620%2C413'
    },
    {
        manufacturer: 'specialized',
        model: 'rockhopper',
        bikeType: 'hardtail',
        wheelSize: 29,
        forkTravel: 100,
        shockTravel: 0,
        htAngle: [68.5],
        link: 'https://www.specialized.com/us/en/shop/bikes/mountain-bikes/trail-bikes/rockhopper/c/rockhopper',
        picLink: 'https://bikerumor.com/wp-content/uploads/2020/05/2021-Specialized-Rockhopper-mountain-bike_affordable-aluminum-alloy-MTB-hardtail_Rockhopper-Expert-tease.jpg'
    },
    {
        manufacturer: 'trek',
        model: 'top fuel',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 120,
        shockTravel: 115,
        htAngle: [67.5,68.0],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/cross-country-mountain-bikes/top-fuel/c/B311/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/TopFuel99XTR_21_32990_A_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'supercaliber',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 100,
        shockTravel: 60,
        htAngle: [69],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/cross-country-mountain-bikes/supercaliber/c/B314/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Supercaliber99XX1_21_33191_A_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'procaliber',
        bikeType: 'hardtail',
        wheelSize: 29,
        forkTravel: 100,
        shockTravel: 0,
        htAngle: [68.8],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/cross-country-mountain-bikes/procaliber/c/B312/',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Procaliber97_21_33265_A_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'x-caliber',
        bikeType: 'hardtail',
        wheelSize: 29,
        forkTravel: 100,
        shockTravel: 0,
        htAngle: [69.5],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/cross-country-mountain-bikes/x-caliber/c/B315/',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/XCaliber9_20_29760_B_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'marlin',
        bikeType: 'hardtail',
        wheelSize: 29,
        forkTravel: 100,
        shockTravel: 0,
        htAngle: [69.5],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/cross-country-mountain-bikes/marlin/c/B321/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Marlin7_21_33148_A_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'slash',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 170,
        shockTravel: 160,
        htAngle: [64.1,64.6],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/trail-mountain-bikes/slash/c/B341/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Slash99XTR_21_34747_C_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'remedy',
        bikeType: 'full suspension',
        wheelSize: 27.5,
        forkTravel: 160,
        shockTravel: 150,
        htAngle: [65.6,66.1],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/trail-mountain-bikes/remedy/c/B331/',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Remedy98275GX_21_33067_B_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'fuel EX',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 140,
        shockTravel: 130,
        htAngle: [66.0,66.5],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/trail-mountain-bikes/fuel-ex/c/B332/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/FuelEX99XTR_21_33409_A_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'roscoe',
        bikeType: 'hardtail',
        wheelSize: 27.5,
        forkTravel: 100,
        shockTravel: 0,
        htAngle: [67.4],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/trail-mountain-bikes/roscoe/c/B342/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Roscoe8_21_28487_B_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'session 27.5',
        bikeType: 'full suspension',
        wheelSize: 27.5,
        forkTravel: 200,
        shockTravel: 210,
        htAngle: [63.6,64.2],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/downhill-mountain-bikes/session/c/B351/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Session8275_20_30267_A_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    },
    {
        manufacturer: 'trek',
        model: 'session 29',
        bikeType: 'full suspension',
        wheelSize: 29,
        forkTravel: 190,
        shockTravel: 190,
        htAngle: [62.1,62.6],
        link: 'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/downhill-mountain-bikes/session/c/B351/?sort=price-desc&pageSize=24&q=%3Arelevance#',
        picLink: 'https://trek.scene7.com/is/image/TrekBicycleProducts/Session99DH29_20_30268_A_Portrait?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440'
    }
]
